<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	  <DuckovPath>/Users/waterlens/Library/Application Support/Steam/steamapps/common/Escape from Duckov/Duckov.app/Contents/Resources/Data</DuckovPath>
  </PropertyGroup>

  <ItemGroup>
		<Reference Include="$(DuckovPath)\Managed\TeamSoda*.dll" />
		<Reference Include="$(DuckovPath)\Managed\Soda*.dll" />
		<Reference Include="$(DuckovPath)\Managed\Unity*.dll" />
		<Reference Include="$(DuckovPath)\Managed\ItemStatsSystem.dll" />
		<Reference Include="$(DuckovPath)\Managed\Plugins.dll" />
		<Reference Include="$(DuckovPath)\Managed\FMODUnity.dll" />
	</ItemGroup>
</Project>
